import type { OrderLanguage } from './orderLocale';
const en = { orbit:'Drag to rotate · use + / − to zoom', top:'Top', side:'Side', reset:'Reset view', play:'Play steps', pause:'Pause', previous:'Previous carton', next:'Next carton', all:'Show all', step:'Carton', list:'Carton list', stale:'Previous valid plan — update the highlighted input before using this result.', number:'Enter a number in this range', whole:'Enter a whole number in this range', above:'Total height must be greater than the base height.', name:'Enter a carton name (1–60 characters).', total:'Use up to 20 carton types and 200 cartons in total.', sample:'Example order — replace these values with your shipment.', optional:'optional' };
export const VIEW_COPY: Record<OrderLanguage, typeof en> = {
 en,
 zh:{orbit:'拖動旋轉 · 用 + / − 縮放',top:'俯視',side:'側視',reset:'重設視角',play:'播放擺箱步驟',pause:'暫停',previous:'上一箱',next:'下一箱',all:'顯示全部',step:'紙箱',list:'紙箱清單',stale:'上一個有效方案 — 請先修正標示的輸入，再使用結果。',number:'請輸入此範圍內的數值',whole:'請輸入此範圍內的整數',above:'總高度必須高於底座高度。',name:'請輸入紙箱名稱（1–60 字）。',total:'最多 20 款、合共 200 箱。',sample:'示範訂單 — 請換成你的貨件資料。',optional:'選填'},
 de:{orbit:'Ziehen zum Drehen · + / − zum Zoomen',top:'Oben',side:'Seite',reset:'Ansicht zurücksetzen',play:'Schritte abspielen',pause:'Pause',previous:'Vorheriger Karton',next:'Nächster Karton',all:'Alle anzeigen',step:'Karton',list:'Kartonliste',stale:'Letzter gültiger Plan — korrigieren Sie die markierte Eingabe vor der Verwendung.',number:'Zahl in diesem Bereich eingeben',whole:'Ganze Zahl in diesem Bereich eingeben',above:'Gesamthöhe muss größer als die Basishöhe sein.',name:'Kartonnamen eingeben (1–60 Zeichen).',total:'Maximal 20 Kartontypen und insgesamt 200 Kartons.',sample:'Beispielauftrag — durch Ihre Sendungsdaten ersetzen.',optional:'optional'},
 fr:{orbit:'Glisser pour pivoter · + / − pour zoomer',top:'Dessus',side:'Côté',reset:'Réinitialiser la vue',play:'Lire les étapes',pause:'Pause',previous:'Carton précédent',next:'Carton suivant',all:'Tout afficher',step:'Carton',list:'Liste des cartons',stale:'Dernier plan valide — corrigez la saisie signalée avant utilisation.',number:'Saisir un nombre dans cet intervalle',whole:'Saisir un entier dans cet intervalle',above:'La hauteur totale doit dépasser celle de la base.',name:'Saisir un nom de carton (1–60 caractères).',total:'Maximum 20 types et 200 cartons au total.',sample:'Commande exemple — remplacez par vos données.',optional:'facultatif'},
 es:{orbit:'Arrastra para girar · + / − para ampliar',top:'Superior',side:'Lateral',reset:'Restablecer vista',play:'Reproducir pasos',pause:'Pausa',previous:'Caja anterior',next:'Caja siguiente',all:'Mostrar todo',step:'Caja',list:'Lista de cajas',stale:'Último plan válido — corrige el campo señalado antes de usarlo.',number:'Introduce un número en este intervalo',whole:'Introduce un entero en este intervalo',above:'La altura total debe superar la altura de la base.',name:'Introduce un nombre de caja (1–60 caracteres).',total:'Máximo 20 tipos y 200 cajas en total.',sample:'Pedido de ejemplo — sustituye los datos por los de tu envío.',optional:'opcional'},
 pt:{orbit:'Arraste para rodar · + / − para ampliar',top:'Topo',side:'Lado',reset:'Repor vista',play:'Reproduzir passos',pause:'Pausa',previous:'Caixa anterior',next:'Caixa seguinte',all:'Mostrar tudo',step:'Caixa',list:'Lista de caixas',stale:'Último plano válido — corrija o campo assinalado antes de usar.',number:'Introduza um número neste intervalo',whole:'Introduza um inteiro neste intervalo',above:'A altura total deve exceder a altura da base.',name:'Introduza um nome de caixa (1–60 caracteres).',total:'Máximo de 20 tipos e 200 caixas no total.',sample:'Pedido de exemplo — substitua pelos dados da sua carga.',optional:'opcional'}
};
